// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcmufcchyqgdsipcxbxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbXVmY2NoeXFnZHNpcGN4YnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDUxNDgsImV4cCI6MjA2MjY4MTE0OH0.evabL4zr2avvyRycWPu9YfdAehfPIDpbCqJOfv8NOEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);